version: "3.7"

services:
    php:
        build: .docker/php
        working_dir: /app
        volumes:
            - .:/app

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sso
            MYSQL_USER: sso
            MYSQL_PASSWORD: sso
        ports:
            - "23306:3306"

    nginx:
        image: nginx:alpine
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/app
